# Generated by Django 6.0.5 on 2026-05-22 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PUBLIC', 'Public Toilet'), ('PRIVATE', 'Private / Paid'), ('HOTEL', 'Hotel / Restaurant'), ('HIGHWAY', 'Highway Rest Stop'), ('PETROL', 'Petrol Station'), ('MALL', 'Shopping Mall'), ('RAILWAY', 'Railway Station'), ('BEACH', 'Beach / Park')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('google_maps_url', models.URLField(blank=True)),
                ('osm_node_id', models.CharField(blank=True, max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('price_inr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operating_hours', models.CharField(blank=True, default='24/7', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('is_women_friendly', models.BooleanField(default=False)),
                ('has_western_toilet', models.BooleanField(default=False)),
                ('has_indian_toilet', models.BooleanField(default=False)),
                ('has_baby_changing', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('verification_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_toilets', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_toilets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToiletPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_public_id', models.CharField(max_length=500)),
                ('image_url', models.URLField(max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='toilets.toilet')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_cover', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('is_positive', models.BooleanField(default=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='toilets.toilet')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='toilet',
            index=models.Index(fields=['status', 'city'], name='toilets_toi_status_c78c87_idx'),
        ),
        migrations.AddIndex(
            model_name='toilet',
            index=models.Index(fields=['latitude', 'longitude'], name='toilets_toi_latitud_b19abe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationvote',
            unique_together={('toilet', 'voter')},
        ),
    ]
