# Generated by Django 6.0.5 on 2026-05-22 09:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toilets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleanliness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('smell', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('privacy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lighting', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('maintenance', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('safety', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('water_availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOMETIMES', 'Sometimes Available'), ('UNAVAILABLE', 'Not Available')], default='AVAILABLE', max_length=15)),
                ('has_soap', models.BooleanField(default=False)),
                ('has_mirror', models.BooleanField(default=False)),
                ('has_dustbin', models.BooleanField(default=False)),
                ('has_hand_dryer', models.BooleanField(default=False)),
                ('has_sanitary_vending', models.BooleanField(default=False)),
                ('crowd_level', models.PositiveSmallIntegerField(help_text='1 = Empty, 5 = Always crowded', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('best_time_to_visit', models.CharField(blank=True, max_length=50)),
                ('admin_note', models.TextField(blank=True)),
                ('visited_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='toilets.toilet')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
